set shell := ["bash", "-cu"]

bootstrap YEAR DAY:
  dotnet new install --force template
  dotnet new aoc -o Year{{YEAR}} -n Year{{YEAR}}.Day{{DAY}}
  dotnet sln add Year{{YEAR}}/Year{{YEAR}}.Day{{DAY}}*/Year{{YEAR}}.Day{{DAY}}*.csproj

build *ARGS:
  dotnet build {{ARGS}}

check *ARGS:
  @echo '{{ style("warning") }}No check for c#{{ NORMAL }}'

clean *ARGS:
  dotnet clean {{ARGS}}

format *ARGS:
  dotnet format {{ARGS}}

lint *ARGS:
  @echo '{{ style("warning") }}No linter for c#{{ NORMAL }}'

run *ARGS:
  dotnet run {{ARGS}}

test *ARGS:
  dotnet test {{ARGS}}

watch *ARGS:
  watchexec -e cs {{ARGS}}
