edition = "2021"
hard_tabs = true
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 128
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
tab_spaces = 2
use_field_init_shorthand = true
