bootstrap YEAR DAY:
  mkdir -p src/year_{{YEAR}}
  cp -n template/lib.rs src/year_{{YEAR}}/day_{{DAY}}.rs

build *ARGS:
  cargo build {{ARGS}}

check *ARGS:
  cargo check {{ARGS}}

clean *ARGS:
  cargo clean {{ARGS}}

format *ARGS:
  cargo fmt {{ARGS}}

lint *ARGS:
  cargo clippy {{ARGS}}

lint-super *ARGS:
  cargo clippy -- -Wclippy::pedantic -Wclippy::restriction -Wclippy::nursery -Wclippy::cargo {{ARGS}}

run *ARGS:
  cargo run {{ARGS}}

test *ARGS:
  cargo test {{ARGS}}

watch *ARGS:
  cargo watch {{ARGS}}
